apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
        - name: mern-server-container
          image: amitazoulay1611/thekitchenette-server:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: mern-server-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: mern-server
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-client
  template:
    metadata:
      labels:
        app: mern-client
    spec:
      containers:
        - name: mern-client-container
          image: amitazoulay1611/thekitchenette-client:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mern-client-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: mern-client
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
